alp late

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -227,6 +227,19 @@ jobs:
             - project/stuff.txt
             - project/.circleci/ansible/inventory.txt
 
+  alpine-late-test:
+    docker:
+      - image: python:3.7-alpine3.11
+    steps:
+      - run:
+          name: Check commands
+          command: |
+            which curl
+      - run:
+          name: Bye
+          command: |
+            exit 1
+
   alpine-test:
     docker:
       - image: python:3.7-alpine3.11
@@ -415,7 +428,7 @@ jobs:
           name: Get backend url
           command: |
             cat .circleci/ansible/inventory.txt
-            export BACKEND_IP=$(tail .circleci/ansible/inventory.txt)
+            export BACKEND_IP=$(tail -1 .circleci/ansible/inventory.txt)
             export API_URL="http://${BACKEND_IP}:3030"
             echo "API_URL = ${API_URL}"
             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
@@ -522,29 +535,27 @@ jobs:
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
-            ## Fetch and prepare the BACKEND_IP env var
-            #export API_URL="http://${BACKEND_IP}:3030"
-            #echo "${API_URL}"
-            #if curl "${API_URL}/api/status" | grep "ok"
-            #then
-            #    return 0
-            #else
-            #    return 1
-            #fi
+            # Fetch and prepare the BACKEND_IP env var
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                return 0
+            else
+                return 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-            #URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-           #echo ${URL} 
-           #if curl -s ${URL} | grep "Welcome"
-           #then
-           #    # Change this to 0 after the job fails
-           #  return 1
-           #else
-           #  return 1
-           #if
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              return 1
+            else
+              return 1
+            if
       # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
@@ -619,6 +630,7 @@ workflows:
     jobs:
 #     - amazon-test
 #     - alpine-test
+      - alpine-late-test
       - build-frontend
       - build-backend
 ###      - patch-node
